### ISSUE TITLE
Integration issue 

### ISSUE THREAD

**Issue by rakeshparihar** [jpcurbelo/human-body-reshape-DL-paper#1]
Model file missing issue, @jpcurbelo  can you help here 
```
InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.3.0 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[1] Finished loading input data (2 photos and basic info) in (0.4 s
[2] Starting to extract the silhouettes from input images (front and side views)
Using cache found in /Users/**********/.cache/torch/hub/pytorch_vision_v0.10.0
** Starting front view
-- Finished front view in 0.1 s
** Starting side view
-- Finished side view in 0.1 s
[2] Finished extracting the silhouettes from input images (front and side) in 1.0 s
Error: File not found - None
```

**Comment by jpcurbelo** [comment]
Hi @rakeshparihar. Thanks for your interest in this repo. It seems the model file is missing. This file should be generated after training the `Extractor` model (`src/extractor/extractor_model_training.py`). I'll try to locate the file I used for the paper results or will rerun the Extractor training and share the necessary file.

**Comment by rakeshparihar** [comment]
@jpcurbelo  any update here ?

**Comment by jpcurbelo** [comment]
Hi, @rakeshparihar. Sorry for the delay, this has been a busy week. I just committed the file `extractor_nn_model.h5` to be loaded. Just make sure that you update the `MODEL_NAME` value. I'm also uploading the file to the [Zenodo dataset](https://zenodo.org/records/11301099). Please, let me know if you find any other issue. Thanks.

**Comment by jpcurbelo** [comment]
@rakeshparihar, any luck with this? Please, let me know to close the issue. Thanks.

**Comment by rakeshparihar** [comment]
@jpcurbelo  still the issue is not resolved, the model file is unable to load is it corrupted ?
